[default.extend-identifiers]
NDKs = "NDKs"

[type.c]
extend-glob = ["*.c", "*.h"]
extend-ignore-words-re = [
    "^BRE|BSE|Pn|clen|doas|ede|inpu|mak|typ|pathc$",
    "^(?i:iterm)$",
]

[type.md]
extend-glob = ["*.md"]
extend-ignore-words-re = [
    "^BSE|ba|ded$",
]

[type.buildmk]
extend-glob = ["build.mk"]
extend-ignore-words-re = ["^ba$"]
