#include "filetype.h"
#include "filetype/types.h"
#include "util/bsearch.h"
#include "util/debug.h"

const char builtin_filetype_names[NR_BUILTIN_FILETYPES][12] = {
    [ADA] = "ada",
    [ASCIIDOC] = "asciidoc",
    [ASM] = "asm",
    [AWK] = "awk",
    [BATCH] = "batch",
    [BIBTEX] = "bibtex",
    [C] = "c",
    [CLOJURE] = "clojure",
    [CMAKE] = "cmake",
    [COBOL] = "cobol",
    [COCCINELLE] = "coccinelle",
    [COFFEESCRIPT] = "coffee",
    [CONFIG] = "config",
    [CONFIG_NTC] = "config-ntc",
    [CSH] = "csh",
    [CSHARP] = "csharp",
    [CSS] = "css",
    [CSV] = "csv",
    [CTAGS] = "ctags",
    [D] = "d",
    [D2] = "d2",
    [DART] = "dart",
    [DEVICETREE] = "devicetree",
    [DIFF] = "diff",
    [DOCKER] = "docker",
    [DOT] = "dot",
    [DTE] = "dte",
    [ELIXIR] = "elixir",
    [ERLANG] = "erlang",
    [FISH] = "fish",
    [GCODE] = "gcode",
    [GDSCRIPT] = "gdscript",
    [GETTEXT] = "gettext",
    [GITCOMMIT] = "gitcommit",
    [GITIGNORE] = "gitignore",
    [GITLOG] = "gitlog",
    [GITNOTE] = "gitnote",
    [GITREBASE] = "gitrebase",
    [GITSTASH] = "gitstash",
    [GLSL] = "glsl",
    [GNUPLOT] = "gnuplot",
    [GO] = "go",
    [GOMODULE] = "gomod",
    [GPERF] = "gperf",
    [GRADLE] = "gradle",
    [GRAPHQL] = "graphql",
    [GROOVY] = "groovy",
    [HARE] = "hare",
    [HASKELL] = "haskell",
    [HCL] = "hcl",
    [HTML] = "html",
    [INDENT] = "indent",
    [INI] = "ini",
    [JAVA] = "java",
    [JAVASCRIPT] = "javascript",
    [JQ] = "jq",
    [JSON] = "json",
    [JSONC] = "jsonc",
    [JULIA] = "julia",
    [KDL] = "kdl",
    [KOTLIN] = "kotlin",
    [LEX] = "lex",
    [LISP] = "lisp",
    [LRC] = "lrc",
    [LUA] = "lua",
    [M4] = "m4",
    [MAIL] = "mail",
    [MAKE] = "make",
    [MARKDOWN] = "markdown",
    [MESON] = "meson",
    [MOONSCRIPT] = "moonscript",
    [NFTABLES] = "nftables",
    [NGINX] = "nginx",
    [NIM] = "nim",
    [NINJA] = "ninja",
    [NIX] = "nix",
    [NONE] = "none",
    [OBJC] = "objc",
    [OCAML] = "ocaml",
    [ODIN] = "odin",
    [PASCAL] = "pascal",
    [PERL] = "perl",
    [PHP] = "php",
    [PKGCONFIG] = "pkg-config",
    [POSTSCRIPT] = "postscript",
    [POWERSHELL] = "powershell",
    [PROTOBUF] = "protobuf",
    [PYTHON] = "python",
    [RACKET] = "racket",
    [ROBOTSTXT] = "robotstxt",
    [ROFF] = "roff",
    [RPMSPEC] = "rpmspec",
    [RST] = "rst",
    [RUBY] = "ruby",
    [RUST] = "rust",
    [SCAD] = "scad",
    [SCALA] = "scala",
    [SCHEME] = "scheme",
    [SCSS] = "scss",
    [SED] = "sed",
    [SH] = "sh",
    [SLINT] = "slint",
    [SQL] = "sql",
    [STEP] = "step",
    [SWIFT] = "swift",
    [TCL] = "tcl",
    [TERMINFO] = "terminfo",
    [TEXINFO] = "texinfo",
    [TEXMFCNF] = "texmfcnf",
    [TEX] = "tex",
    [TLVERILOG] = "tl-verilog",
    [TMUX] = "tmux",
    [TOML] = "toml",
    [TSV] = "tsv",
    [TYPESCRIPT] = "typescript",
    [TYPST] = "typst",
    [VALA] = "vala",
    [VCARD] = "vcard",
    [VERILOG] = "verilog",
    [VHDL] = "vhdl",
    [VIML] = "viml",
    [WEECHATLOG] = "weechatlog",
    [XML] = "xml",
    [XRESOURCES] = "xresources",
    [YACC] = "yacc",
    [YAML] = "yaml",
    [ZIG] = "zig",
};

UNITTEST {
    static_assert(NR_BUILTIN_FILETYPES < 256);
    CHECK_BSEARCH_STR_ARRAY(builtin_filetype_names);

    for (size_t i = 0; i < ARRAYLEN(builtin_filetype_names); i++) {
        const char *name = builtin_filetype_names[i];
        if (unlikely(!is_valid_filetype_name(name))) {
            BUG("invalid name at builtin_filetype_names[%zu]: \"%s\"", i, name);
        }
    }
}
